/**
 * `openlabor upload` / `openlabor download` — move files in and out of an
 * employee's workspace.
 *
 * Both are thin: the API already knows how to zip a folder and how to write a
 * file. What was missing was a way to ask for either without a browser, which
 * is what turns "migrate my team onto OpenLabor" from a day of drag-and-drop
 * into one command.
 */

import { readFileSync, writeFileSync, statSync, readdirSync, existsSync } from 'fs';
import { join, basename, relative, sep } from 'path';
import { requireAuth } from './auth.js';
import { createClient } from './api.js';
import { API_URL } from './config.js';
import { getEmployee } from './pilot.js';

/** Files that are never worth moving between machines. */
const SKIP_NAMES = new Set(['.DS_Store', 'Thumbs.db', '.git', 'node_modules', '__pycache__']);
/** The workspace files OpenLabor generates per employee — never overwrite them. */
const GENERATED = new Set([
  'AGENTS.md', 'SOUL.md', 'IDENTITY.md', 'TOOLS.md', 'USER.md',
  'HEARTBEAT.md', 'MEMORY.md', 'DREAMS.md', 'BOOTSTRAP.md',
]);
/** Matches the server-side WRITE_FILE ceiling. */
const MAX_BYTES = 25 * 1024 * 1024;

function client() {
  return createClient({ apiUrl: API_URL, apiKey: requireAuth().api_key });
}

/** Every file under `dir`, depth-first, as {abs, rel} pairs. */
function walk(dir, base = dir) {
  const out = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (SKIP_NAMES.has(entry.name) || entry.name.startsWith('.')) continue;
    const abs = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(abs, base));
    else if (entry.isFile()) out.push({ abs, rel: relative(base, abs).split(sep).join('/') });
  }
  return out;
}

/**
 * Upload a file or a whole directory into an employee's workspace.
 *
 * onFile({ rel, bytes, status }) is called per file so the caller can print
 * progress: a 200-file upload that prints nothing looks like a hang.
 */
export async function upload(employeeIdOrName, localPath, opts = {}) {
  const { dir: targetDir = '', overwrite = false } = opts;

  if (!existsSync(localPath)) throw new Error(`No such file or directory: ${localPath}`);
  const employee = await getEmployee(employeeIdOrName);
  const api = client();

  const stat = statSync(localPath);
  const files = stat.isDirectory()
    ? walk(localPath)
    : [{ abs: localPath, rel: basename(localPath) }];

  if (files.length === 0) throw new Error(`Nothing to upload from ${localPath}`);

  const results = { uploaded: 0, skipped: [], failed: [] };

  for (const f of files) {
    const dest = targetDir ? `${targetDir.replace(/\/+$/, '')}/${f.rel}` : f.rel;

    // Refuse the generated persona files outright. Overwriting SOUL.md with the
    // one from another system replaces who the employee is, silently.
    if (GENERATED.has(basename(dest))) {
      results.skipped.push({ rel: dest, why: 'generated by OpenLabor' });
      opts.onFile?.({ rel: dest, status: 'skipped' });
      continue;
    }

    const buf = readFileSync(f.abs);
    if (buf.length > MAX_BYTES) {
      results.skipped.push({ rel: dest, why: `too large (${(buf.length / 1048576).toFixed(1)}MB)` });
      opts.onFile?.({ rel: dest, status: 'skipped' });
      continue;
    }

    try {
      await api.post('/api/connectors/workspace/execute', {
        employeeId: employee.id,
        tool: 'WRITE_FILE',
        args: { path: dest, content_base64: buf.toString('base64'), overwrite },
      });
      results.uploaded++;
      opts.onFile?.({ rel: dest, bytes: buf.length, status: 'ok' });
    } catch (err) {
      // An existing file is a normal outcome without --overwrite, not a crash.
      const why = /already exists/i.test(err.message) ? 'exists (use --overwrite)' : err.message;
      results.failed.push({ rel: dest, why });
      opts.onFile?.({ rel: dest, status: 'failed', why });
    }
  }

  return { employee, ...results };
}

/**
 * Download an employee's whole workspace as a zip.
 *
 * The server streams a zip for any directory, so the entire workspace is one
 * request — no per-file loop, and no chance of a half-copied tree.
 */
export async function download(employeeIdOrName, destPath) {
  const creds = requireAuth();
  const employee = await getEmployee(employeeIdOrName);

  // The workspace folder is named after template_id (custom hires carry their
  // own id there), which is what the API resolves paths against.
  const folder = employee.template_id || employee.id;
  const url = `${API_URL}/api/workspace/download?path=${encodeURIComponent(folder)}`;

  const res = await fetch(url, { headers: { 'X-API-Key': creds.api_key } });
  if (!res.ok) {
    const body = await res.text().catch(() => '');
    if (res.status === 403) {
      throw new Error(
        'Forbidden. Downloading a workspace needs a workspace key — run `openlabor login` ' +
        '(browser) rather than logging in with an employee key.',
      );
    }
    throw new Error(`Download failed: ${res.status} ${body.slice(0, 200)}`);
  }

  const out = destPath || `${folder}-workspace.zip`;
  writeFileSync(out, Buffer.from(await res.arrayBuffer()));
  return { employee, path: out, bytes: statSync(out).size };
}
